export const CHOOSE_SINGLE_FILE = 'CHOOSE_SINGLE_FILE'
export const PARSE_PROTO_FILE = 'PARSE_PROTO_FILE'
export const TURN_ON_GRPC_SERVER = 'TURN_ON_GRPC_SERVER'
export const TURN_OFF_GRPC_SERVER = 'TURN_OFF_GRPC_SERVER'
